# Generated by Django 5.0.7 on 2024-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifactorauth',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
