# Generated by Django 5.0.7 on 2024-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0002_multifactorauth_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
