# Generated by Django 6.1.1 on 2026-09-16 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0004_passkey_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_expires_at', models.DateTimeField()),
                ('link_expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AccessCode',
        ),
        migrations.RemoveField(
            model_name='passkey',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='dj_waanvers_account_8b001c_idx',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Passkey',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
