# Generated by Django 5.1.1 on 2025-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0004_remove_resetpasswordcode_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
