# Generated by Django 5.1.1 on 2025-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0007_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multifactorauth',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
