# Generated by Django 5.1.1 on 2025-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0008_alter_multifactorauth_recovery_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'Verification Code', 'verbose_name_plural': 'Verification Codes'},
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Verification Code'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email_address',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
