# Generated by Django 5.2.4 on 2025-08-12 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0016_logincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Login Code', 'verbose_name_plural': 'Login Codes'},
        ),
        migrations.AlterField(
            model_name='logincode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
