# Generated by Django 5.2.4 on 2025-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0018_webauthnchallenge_webauthncredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthnchallenge',
            name='challenge',
            field=models.BinaryField(max_length=100, unique=True),
        ),
    ]
