# Generated by Django 5.2.4 on 2025-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0019_alter_webauthnchallenge_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
    ]
