# Generated by Django 5.2.4 on 2025-08-15 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0020_alter_verificationcode_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleStateToken',
        ),
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='account',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expires At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.DeleteModel(
            name='MultiFactorAuth',
        ),
        migrations.DeleteModel(
            name='ResetPasswordToken',
        ),
    ]
