# Generated by Django 5.2.4 on 2025-08-15 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0021_delete_googlestatetoken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={'verbose_name': 'Login Code', 'verbose_name_plural': 'Login Codes'},
        ),
        migrations.RemoveField(
            model_name='logincode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='logincode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
