version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "coverage"
      - dependency-name: "django"
      - dependency-name: "django-cors-headers"
      - dependency-name: "django-dotenv"
      - dependency-name: "djangorestframework"
      - dependency-name: "flake8"
      - dependency-name: "mailersend"
      - dependency-name: "phonenumbers"
      - dependency-name: "pyjwt"
      - dependency-name: "cryptography"
    ignore:
      # Stay on Django 6 until you decide to support 7
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
