# Generated by Django 5.1.1 on 2025-01-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email',
            new_name='email_address',
        ),
    ]
