# Generated by Django 5.1.1 on 2025-01-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_email_verified_account_password_last_updated_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_address',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='E.164 format recommended (+1234567890)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_index=True, help_text='Required. 10 characters or fewer.', max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', None), _negated=True), fields=('phone_number',), name='unique_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('email_address', None), _negated=True), fields=('email_address',), name='unique_email_address'),
        ),
    ]
