# Generated by Django 5.1.1 on 2025-01-12 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_email_address_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_phone_number',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_email_address',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_account_username_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email_address'], name='accounts_account_email_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone_number'], name='accounts_account_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', None), _negated=True), fields=('phone_number',), name='accounts_account_unique_phone'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('email_address', None), _negated=True), fields=('email_address',), name='accounts_account_unique_email'),
        ),
    ]
