# Generated by Django 5.1.1 on 2025-03-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_account_completed',
            field=models.BooleanField(default=False),
        ),
    ]
