# Generated by Django 5.1.1 on 2025-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_is_account_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
