# Generated by Django 5.1.1 on 2025-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_account_password_last_updated'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='accounts_account_must_have_contact',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_index=True, max_length=35, unique=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('email_address__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='accounts_account_must_have_contact'),
        ),
    ]
