# Generated by Django 5.1.1 on 2025-06-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_accounts_account_must_have_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_account_completed',
        ),
    ]
