# Generated by Django 5.2.4 on 2025-08-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_account_is_account_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password_last_updated',
        ),
    ]
