# Generated by Django 5.2.4 on 2025-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_password_last_updated'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='accounts_account_unique_phone',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='accounts_account_unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='accounts_account_must_have_contact',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_account_phone_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number_verified',
        ),
        migrations.AlterField(
            model_name='account',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
