# Generated by Django 5.2.4 on 2026-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_region',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Region'),
        ),
    ]
