# Generated by Django 5.2.4 on 2026-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_phone_number_account_phone_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
