# Generated by Django 5.2.4 on 2026-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_phone_verified'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_account_username_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_account_email_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
    ]
