# Generated by Django 6.1.1 on 2026-09-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_account_accounts_account_username_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
