name: Django CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: test_user
                    POSTGRES_PASSWORD: test_password
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U test_user -d test_db"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Migrations
              env:
                  DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
              run: |
                  python demo/manage.py migrate

            - name: Run Tests with Coverage
              env:
                  DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
              run: |
                  coverage run --source='.' demo/manage.py test
                  coverage report
